language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-codepen' ]; then cd .. && eval "mv $currentfolder generator-codepen" && cd generator-codepen; fi
